#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Joice's 博客"
# Short bio or description (displayed in the header)
description: "人人为我，我为人人!"

